//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQACustomerArea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public int AccountId { get; set; }
        public int FunctionId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Function Function { get; set; }
    }
}
